Create hello world
Al-Amin-Khan-Shakil/Hello-World pull request #1
Opened 2023-04-27 17:02 UTC by Al-Amin-Khan-Shakil

This pull request is for a greeting project to the Microverse community.

2023-04-27 17:39 UTC, vickymarz requested changes
Hi @Al-Amin-Khan-Shakil, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] I want to bring to your notice that this is not a hello world project to greet you to Microverse as you have specified 😄 but rather this project is to teach you how to setup linters and also how to make your repo look professional. In light of these, i will recommend thst you chsnge your pull request descriptions such as the pull request title, summary and branch name to better describe the activity or changes you introduced to your project 👍🏽 .

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 08:27 UTC, Al-Amin-Khan-Shakil commented
As you mentioned avobe ( "i will recommend thst you chsnge your pull request descriptions such as the pull request title, summary and branch name to better describe the activity or changes you introduced to your project".) I changed my feature branch name and that lead my PR to Closed that is why I am reopening my Pull Request.

2023-04-28 08:50 UTC, LionRouge1 requested changes
Hi @Al-Amin-Khan-Shakil, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-28 08:50 UTC, LionRouge1 commented on README.md
> +  <h3><b>Microverse README Template</b></h3>
[OPTIONAL]
- [ ] Kindly change the title of your README file to suit your project. That will make it looks more professional. Therefore remove the "Microverse README Template" and add the name of your project.

2023-04-28 08:50 UTC, LionRouge1 commented on README.md
> +  - [🚀 Live Demo](#live-demo)
- [ ] As mentioned by the previous reviewer, kindly remove the "Live Demo" title from the Table of Contents to avoid having links that are not working in your README file.

> * [ ]  Kindly remove this live demo link since the section is not available in your readme 👍🏽

2023-04-28 10:03 UTC, algerina approved these changes
Hi @Al-Amin-Khan-Shakil ,

Great job so far! 

May I highlight the following: 
- [x] Your project looks fine👏  ✔️ 
- [x] You set up all the requirements requested by the previous TSE's✔️ 
- [x ]  Linters are passing


## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-04-28 10:41 UTC, merged